name: Linux (Vulkan)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Apt Update
      run: sudo apt-get update
    - name: Apt Install
      run: sudo apt install make clang libvulkan-dev libgtk-3-dev --yes --quiet
    - name: Compile
      run: |
        cd paint
        ../base/make --compile
