name: Windows (Direct3D12)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: |
        cd paint
        ../base/make --compile
